blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('by/<username>/', views.UserTwitt.as_view(), name = 'for_user'),
    path('by/<username>/<int:pk>', views.SingleTwitt.as_view(), name = "singletwitt"),
    path('new/', views.CreateTwitt.as_view(), name = 'createtwitt'),
    path('update/<int:pk>', views.UpdateTwitt.as_view(), name = 'updatetwitt'),
    path('delete/<int:pk>', views.DeleteTwitt.as_view(), name = 'deletetwitt'),
    path('profile/', views.edit_photo, name = 'profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home/', views.listing, name = 'listing'),
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('search/', views.search, name="search"),
    path('home/', views.TestPage.as_view(), name="home"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('blog/', include('blog.urls', namespace = 'blog')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib import auth
from django.utils import timezone


User = settings.AUTH_USER_MODEL

class Follow(models.Model):
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
    follow_user = models.ForeignKey(User, related_name='follow_user', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #user.profile

    background_pic = models.ImageField(default='default_background.jpg', upload_to='profile_pics',blank=True)
    profile_pic = models.ImageField(default='default.png', upload_to='profile_pics',blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


    @property                                                                # Using property we get a list of followers
    def followers_list(self):
        return Follow.objects.filter(follow_user=self.user)

    @property                                                               # Using property we get a number of following
    def following(self):
        return Follow.objects.filter(user=self.user).count()


#  Django signals to automatically create a user profile when a user object is created
def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        profile, is_created = Profile.objects.get_or_create(user = instance)

post_save.connect(post_save_user_receiver, sender=User)

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone

# Create your models here.

from django.contrib.auth import get_user_model
User = get_user_model()



class Twitt(models.Model):
    author = models.ForeignKey(User, related_name="twitts", on_delete=models.CASCADE)
    text = models.TextField(max_length=280)
    publish_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text[:10]


    @property
    def number_of_comments(self):
        return Comment.objects.filter(twitt_connected=self).count()



class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    twitt_connected = models.ForeignKey(Twitt, on_delete=models.CASCADE)
    text = models.TextField(max_length=280)
    publish_date = models.DateTimeField(default=timezone.now)

blog/forms.py
from django import forms
from .models import Comment
from accounts.models import Profile


class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class ImageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["profile_pic", "background_pic"]
        exclude = ['user']                              # exclude user field

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
# from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import(LoginRequiredMixin, PermissionRequiredMixin)
from django.contrib import messages
from django.views import generic
from django.urls import reverse_lazy, reverse
from . import models
from accounts.models import Profile, Follow
# from braces.views import SelectRelatedMixin
# from django.http import Http404
from django.contrib.auth import get_user_model
from .forms import NewCommentForm, ImageForm


User = get_user_model()


class CreateTwitt(LoginRequiredMixin, generic.CreateView):
    fields = ("text",)
    model = models.Twitt
    template_name = 'blog/twitt_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:for_user", kwargs={"username": self.request.user.username})

######################################################################################

class SingleTwitt(generic.DetailView):
    model = models.Twitt
    template_name = 'blog/twitt_detail.html'
    context_object_name = 'twitt'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        comments_connected = models.Comment.objects.filter(twitt_connected=self.get_object()).order_by('-publish_date')         # get all comments that are connected to the given Twitt
        data['comments'] = comments_connected
        data['form'] = NewCommentForm(instance=self.request.user)                           # set form from forms.py
        return data

    def post(self, request, *args, **kwargs):
        new_comment = models.Comment(text=request.POST.get('text'), author=self.request.user, twitt_connected=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)

######################################################################################

class UserTwitt(generic.ListView):
    model = models.Twitt
    template_name = 'blog/user_twitt_list.html'
    image_form = ImageForm

    def visible_user(self):
        return get_object_or_404(User, username=self.kwargs.get('username'))

    def get_queryset(self):                                                                   #returns objects (twitts) sorted by date of the user whose profile we are on
        twitt_user = get_object_or_404(User, username=self.kwargs.get('username'))
        return models.Twitt.objects.filter(author=twitt_user).order_by('-publish_date')

    def get_context_data(self, **kwargs):

        if self.request.user.username == '' or self.request.user is None:
            can_follow = False
        else:
            can_follow = (Follow.objects.filter(user=self.request.user,
                                                follow_user=self.visible_user()).count() == 0)    # set can_follow as the Follow object of the logged in user with follow_user for the user whose profile is visiting == 0

        data = super().get_context_data(**kwargs)
        data['user_profile'] = self.visible_user()
        data['can_follow'] = can_follow
        return data

    def post(self, request, *args, **kwargs):
        if request.user.id is not None:
            follows_between = Follow.objects.filter(user=request.user,
                                                    follow_user=self.visible_user())        # set follows_between as the Follow object of the logged in user with follow_user for the user whose profile is visiting

            if 'follow' in request.POST:                                                            # if 'follow' set new_relation as the Follow object of the logged in user with follow_user for the user whose profile is visiting
                    new_relation = Follow(user=request.user, follow_user=self.visible_user())       # then if follows_between == 0, make that new_relation and save it
                    if follows_between.count() == 0:
                        new_relation.save()
            elif 'unfollow' in request.POST:                                                        # if 'unfollow' that mean follows_between is > 0 and we delete that particularly follows_between --> switching
                    if follows_between.count() > 0:
                        follows_between.delete()

        return self.get(self, request, *args, **kwargs)

######################################################################################

class DeleteTwitt(LoginRequiredMixin, generic.DeleteView):
    model = models.Twitt

    def get_success_url(self):
        return reverse_lazy("blog:for_user", kwargs = {'username':self.request.user.username})


    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")          # after delete show message
        return super().delete(*args, **kwargs)

######################################################################################

class UpdateTwitt(LoginRequiredMixin, generic.UpdateView):
    model = models.Twitt
    fields = ['text']
    template_name = 'blog/twitt_update.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:singletwitt", kwargs={"username": self.request.user.username, "pk": self.object.pk})

######################################################################################

def edit_photo(request):
    if request.method == "POST":
        profile_form = ImageForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, f'Your profile has been updated!')
            return redirect('/home/')

    else:
        profile_form = ImageForm(instance=request.user.profile)

    context = {'profile_form':profile_form}
    return render(request, 'blog/profile.html', context)

blog/templates/blog/_twitt.html
{% load static %}

<div class="row twitt_list infinite-item">

  <div class="twitt_logo" onclick = "location.href='{% url 'blog:for_user' username=twitt.author.username %}';" style = "cursor:pointer;">
      <img class="profile_img" src="{{twitt.author.profile.profile_pic.url}}" alt="">
  </div>

  <div class="profie_nick">
    <div class="info">
      <p id = "twitt_username">@{{ twitt.author.username }}</p>
      <p id = "twitt_username2">@{{ twitt.author.username }}</p>
      <p id = "twitt_date">Date: {{twitt.publish_date}}</p>
      <p id = "comment_info"><i class="far fa-comment"></i> Comments: {{twitt.number_of_comments}}</p>
    </div>
    <div class="text" onclick = "location.href='{% url 'blog:singletwitt' username=twitt.author.username pk=twitt.pk %}';" style = "cursor:pointer;">
      <p>{{ twitt.text|safe }}</p>
    </div>
  </div>

</div>

blog/templates/blog/blog_base.html
{% extends "home.html" %}
{% block content %}


{% block twitt_content %}
{% endblock %}


{% endblock %}

blog/templates/blog/profile.html
{% extends "blog/blog_base.html" %}
{% load static %}

{% block twitt_content %}

<div class="container" style = margin-top:72px>
  <div class="row justify-content-center">

    <div class="col-sm-8">
      <h4><i class="fas fa-pen"></i> Update your profile photos</h4>
      <br>

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="photos_edit">
          <label for="id_profile_pic"><strong>Profile pic</strong></label>
          <p>Currently:</p>
          <img src="{{ request.user.profile.profile_pic.url }}" alt="" style="height:120px; width:120px; border-radius:50%; margin-bottom:20px">
          <p>Change: <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic"></p>
        </div>

        <br>

        <div class="photos_edit">
          <label for="id_background_pic"><strong>Background pic</strong></label>
          <p>Currently:</p>
          <img src="{{ request.user.profile.background_pic.url }}" alt="" style="height:120px; width:360px; margin-bottom:20px">
          <p>Change: <input type="file" name="background_pic" accept="image/*" id="id_background_pic"></p>
        </div>

        <input class = "twittbf" type="submit" name="" value="Update" style="margin-bottom:50px;">
      </form>

    </div>
      {% include "right_column.html" %}
  </div>
</div>
{% endblock %}

blog/templates/blog/twitt_confirm_delete.html
{% extends "blog/blog_base.html" %}
{% load static %}

{% block twitt_content %}
<div class="container" style = "margin-top:72px">
  <div class="row justify-content-center">

    <div class="col-sm-8">
        <h4><i class="fa fa-remove" aria-hidden="true"> </i> Are you sure you want to delete this twitt?</h4>


      {% include "blog/_twitt.html" with twitt=object hide_delete=True %}

      <form method="POST">
         {% csrf_token %}
         <input type="submit" value="Confirm Delete" class="btn twittbf">
         <a href="{% url 'blog:for_user' username=twitt.author.username %}" class="btn twittb">Cancel</a>
      </form>

    </div>

    {% include "right_column.html" %}


  </div>
</div>
{% endblock %}

blog/templates/blog/twitt_detail.html
{% extends "blog/blog_base.html" %}
{% load bootstrap4 %}
{% load static %}

<!-- ######################################################################################### -->

{% block twitt_content %}

<div class="container" style = margin-top:72px>
  <div class="row justify-content-center">

    <div class="col-sm-8">

      {% include "blog/_twitt.html" %}


      {% if user.is_authenticated and twitt.author == user and not hide_delete %}

        <a href="{% url 'blog:updatetwitt' pk=twitt.pk %}" title="update" class="btn twittbf">
          <span class="fa fa-pencil" aria-hidden="true"></span>
          <span class="icon-label">Update</span>
        </a>

        <a href="{% url 'blog:deletetwitt' pk=twitt.pk %}" title="delete" class="btn twittb">
          <span class="fa fa-remove" aria-hidden="true"></span>
          <span class="icon-label">Delete</span>
        </a>
      {% endif %}

      <div class="">

        <div class="row header">
          <h4>Comments:</h4>
        </div>

        {% for comment in comments %}

          <div class="row twitt_list">

            <div class="twitt_logo" onclick = "location.href='{% url 'blog:for_user' username=comment.author.username %}';" style = "cursor:pointer;">
              <img class="profile_img" src="{{comment.author.profile.profile_pic.url}}" alt="">
            </div>

            <div class="profie_nick">
              <div class="info">
                <p id = "twitt_username">@{{ comment.author.username }}</p>
                <p id = "twitt_username2">@{{ comment.author.username }}</p>
                <p id = "twitt_date">Date: {{ comment.publish_date | date:"H:i l, d.m.Y" }}</p>
              </div>
              <div class="text">
                <p>{{ comment.text }}</p>
              </div>
            </div>

          </div>

        {% endfor %}
      </div>

      <div class="">
          {% if user is not None %}
            <div class="">
              <div class="row header">
                <h4>Add Comment:</h4>
              </div>

              <form class="form-group" method="post">
                {% csrf_token %}
                <div class="form-group twitt_list">
                  <label for="id_text"></label>
                  <textarea name="text" cols="10" rows="5" maxlength="280" class="form-control" placeholder="Your comment..." title="" required="" id="id_text"></textarea>
                </div>
                <div class="form-group">
                  <button type="submit" class="btn twittbf">Add Comment</button>
                </div>
              </form>

            </div>
          {% endif %}
      </div>

    </div>

    {% include "right_column.html" %}

  </div>
</div>
{% endblock %}

blog/templates/blog/twitt_form.html
{% extends "blog/blog_base.html" %}
{% load bootstrap4 %}


{% block twitt_content %}

<div class="container" style = "margin-top:72px">
  <div class="row justify-content-center">
    <div class="col-sm-8">
        <h4><i class="fas fa-plus"></i> Create Twitt</h4>

        <form class="form-group" action="{% url 'blog:createtwitt' %}" method="post">
          {% csrf_token %}
          <div class="form-group twitt_list">
            <label for="id_text"></label>
            <textarea name="text" cols="10" rows="5" maxlength="280" class="form-control" placeholder="What's up?" title="" required="" id="id_text"></textarea>
          </div>
          <div class="form-group">
            <button type="submit" class="btn twittbf">Publish Twitt</button>
          </div>
        </form>

    </div>

    {% include "right_column.html" %}

  </div>
</div>

{% endblock %}

blog/templates/blog/twitt_update.html
{% extends "blog/blog_base.html" %}
{% load bootstrap4 %}
{% load static %}


{% block twitt_content %}
<div class="container" style = "margin-top:72px">
  <div class="row justify-content-center">
    <div class="col-sm-8">
        <h4><i class="fa fa-pencil"></i> Update your Twitt</h4>

      <form class="form-group" action="{% url 'blog:updatetwitt' pk=twitt.pk %}" method="post">
        {% csrf_token %}
        <div class="form-group twitt_list">
          <label for="id_text"></label>
          <textarea name="text" cols="10" rows="5" maxlength="280" class="form-control" placeholder="Text" title="" required="" id="id_text">{{ twitt.text|safe }}</textarea>
        </div>

        <div class="form-group">
          <button type="submit" class="btn twittbf"><span class="fa fa-pencil" aria-hidden="true"></span> Update</button>
          <a href="{% url 'blog:for_user' username=twitt.author.username %}" class="btn twittb">Cancel</a>
        </div>
      </form>


    </div>

    {% include "right_column.html" %}

  </div>
</div>
{% endblock %}

blog/templates/blog/user_twitt_list.html
{% extends "blog/blog_base.html" %}
{% load static %}
{% block twitt_content %}

<div class="container" style = margin-top:72px>
  <div class="row justify-content-center">

    <div class="col-sm-8">

      <div class="background_photo">
        <img class = "background_photo" src="{{user_profile.profile.background_pic.url}}" alt="">

        {% if request.user.username == user_profile.username %}
          <button class = "edit_bgp" type="submit" name="button"><a href="{% url 'blog:profile' %}"><i class="fas fa-pen"></i></a></button>
        {% endif %}

      </div>
      <div class="row img_profile_follow">
        <div class="follow_btn">

          <form method="post">
            {% csrf_token %}
            <div class="form-group">

              <button class = "twittb" type="submit" name="{% if can_follow %}follow{% else %}unfollow{% endif %}">
                {% if can_follow %}Follow{% else %}Unfollow{% endif %}</button>

            </div>
          </form>

          <div class="logo">
            <a href="{% url 'blog:for_user' username=user_profile.username %}"><img src="{{user_profile.profile.profile_pic.url}}" alt=""> </a>

            {% if request.user.username == user_profile.username %}

            <button class = "edit_pl" type="submit" name="button" ><a href="{% url 'blog:profile' %}"><i class="fas fa-pen"></i></a></button>
            {% endif %}

          </div>
        </div>
      </div>
      <div class="profile_data">
        <p id = "username">@{{ user_profile.username }}</p>
        <p id = "username2">@{{ user_profile.username }}</p>
        <p id = "profile_created_date"><span class="fa fa-calendar" aria-hidden="true"></span> Joined: {{user_profile.date_joined |date:'Y/m/d'}}</p>
        <p style="display:inline-block"><span style = "font-weight: bold;">{{ user_profile.profile.following }} </span>Follow</p>
        <p id="followed_info" style="display:inline-block"><span style = "font-weight: bold;">{{ user_profile.profile.followers_list.count }} </span>Followed</p>
      </div>
      <div class="row header">
        <h4>Twitts</h4>
      </div>


<!-- ############## TWITTS -->

  {% for twitt in twitt_list %}
    {% include "blog/_twitt.html" %}
  {% endfor %}
    </div>

    {% include "right_column.html" %}

  </div>
</div>
{% endblock %}