accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'), # Uses django login view
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),                                # Uses django logout view
    path('signup/', views.SignUp.as_view(), name="signup"),                                         
]

blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('by/<username>/', views.UserTwitt.as_view(), name = 'for_user'),
    path('by/<username>/<int:pk>', views.SingleTwitt.as_view(), name = "singletwitt"),
    path('new/', views.CreateTwitt.as_view(), name = 'createtwitt'),
    path('update/<int:pk>', views.UpdateTwitt.as_view(), name = 'updatetwitt'),
    path('delete/<int:pk>', views.DeleteTwitt.as_view(), name = 'deletetwitt'),
    path('profile/', views.edit_photo, name = 'profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home/', views.listing, name = 'listing'),
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('search/', views.search, name="search"),
    path('home/', views.TestPage.as_view(), name="home"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('blog/', include('blog.urls', namespace = 'blog')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- MY_CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css'%}">

    <!-- FONTAWESOME -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <title>Twitter. To się dzieje. / Twitter</title>
  </head>
  <body>

    <div>
      {% block content %}

      {% endblock %}
    </div>

  </body>
</html>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <!-- jQuery -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.js"
      integrity="sha256-DrT5NfxfbHvMHux31Lkhxg42LY6of8TaYyK50jnxRnM="
      crossorigin="anonymous"></script>

    <!-- BOOTSTRAP -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <!-- MY_CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">

    <!-- FONTAWESOME -->
    <!-- <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"> -->
    <script src="https://kit.fontawesome.com/c34f7449bf.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="{% static 'img/logo.png' type='image/x-icon' %}">


    <title>Twitter. To się dzieje. / Twitter</title>

<!-- ################################# jQuery ################################# -->
    <script type="text/javascript">
    $(document).ready(function() {
    	// jQuery code

    	///////////////// fixed menu on scroll for desctop
        if ($(window).width() > 992) {

            var navbar_height =  $('.navbar').outerHeight();

            $(window).scroll(function(){
                if ($(this).scrollTop() > 50) {
                     // $('#navbar_top').addClass("fixed-top");
                     $('#border_nav').addClass("border_nav");
                }else{
                    // $('#navbar_top').removeClass("fixed-top");
                    $('#border_nav').removeClass("border_nav");
                }
            });
        } // end if
    }); // jquery end
    </script>
<!-- ################################# -->
    <script >
      $(document).ready(function(){
      	$("span[name=copy_pre]").click(function() {
      		var id = $(this).attr('id');
      		var el = document.getElementById(id);
      		var range = document.createRange();
      		range.selectNodeContents(el);
      		var sel = window.getSelection();
      		sel.removeAllRanges();
      		sel.addRange(range);
      		document.execCommand('copy');
      		// alert("Contents copied to clipboard.");
      		return false;
      	});
      });
    </script>
<!-- ################################# -->
    <script type="text/javascript">
      function copyinfo() {
        function showinfo(){
          $(".infocopy").css('opacity', '1')
          $(".infocopy").css('transition', 'opacity 0.5s ease-in')
          setTimeout(function(){ $(".infocopy").css('opacity', '0') }, 1000);
        }
        var info = document.getElementById('myemail');
        info.addEventListener("click", function() { showinfo(); });

        }
    </script>
<!-- ################################# jQuery END ################################# -->
</head>

<body style="width: auto !important; overflow-y: scroll">
{% load bootstrap4 %}
	<header>

		<div class="container-fluid p-0">
			<nav class="navbar navbar-expand-md fixed-top navbar-light" id = "border_nav">
				<div class="container mynav">

					<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static  'img/logo.png' %}" alt="logo"></a>

					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainmenu" aria-controls="mainmenu" aria-expanded="false" aria-label="Przełącznik nawigacji">
						<span class="navbar-toggler-icon"></span>
					</button>

					<div class="collapse navbar-collapse mynav" id="mainmenu">

						<form class="form-inline" method="get" action="{% url 'search' %}">
							<input class="form-control mr-1" name = "q" type="text" placeholder="Search..." aria-label="Search" value = {{query}}>
						</form>

						{% if user.is_authenticated %}
							<a class="nav-item nav-link" href="{% url 'blog:createtwitt' %}" class="btn btn-simple"><strong>New Twitt</strong></a>
							<a class="nav-item nav-link" href="{% url 'blog:for_user' username=user.username %}" class="btn btn-simple"><strong>My Twitts</strong></a>
							<a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple"><strong>Log out </strong><i class="fas fa-sign-out-alt"></i></a>
						{% else %}
							<a role = "button" class="nav-item nav-link twittb" href="{% url 'login' %}" class="btn btn-simple">Log in</a>
							<a role = "button" class="nav-item nav-link twittbf" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
						{% endif %}
					</div>

				</div>
			</nav>
		</div>

	</header>

	<main>
    {% block content %}
    <div class="container" style = margin-top:72px>
      <div class="row justify-content-center">

        <div class="col-sm-8">
          <img src="{% static  'img/clouds.png' %}" alt="" style="width:100%; height: 206px; margin-bottom:15px;">
          <div class="infinite-container">
            {% for twitt in page_obj %}
              {% include "blog/_twitt.html" %}
            {% endfor %}
          </div>

          <div class="pagination" style="margin-bottom: 25px;">
              <span id ="change_page" class="step-links">
                  {% if page_obj.has_previous %}
                      <a href="?page=1">&laquo; first</a>
                      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}

                  <span class="current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>

                  {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}">next</a>
                      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                  {% endif %}
              </span>
          </div>

        </div>

        {% include "right_column.html" %}

      </div>
    </div>
    {% endblock %}
	</main>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <div class="container-fluid p-0">
    <div class="container ileft">
        <h4><p><span class="fa fa-search"> </span> Obserwuj to, co Cię interesuje.</p>
          <br><p><span class="fa fa-users"> </span> Dowiedz się, o czym mówią inni.</p>
          <br><p><span class="fa fa-comments-o" ></span> Dołącz do rozmowy.</p>
        </h4>
    </div>
    <div class="container iright">
      <!-- <form class="ilogin" method="post">
        <input id = "abc" type="text" placeholder="Username">
        <input id = "abc" type="text" placeholder="Password">
        <input class = "buttons btn btn-primary" type="submit" name="login" value="Login">
      </form> -->
      <div id = 'signup'>
        <a href="{% url 'home' %}"><img src="{% static  'img/logo.png' %}" alt="logo"></a>
        <h4><b>Zobacz, co się dzieje w tej chwili na świecie</b></h4><br>
        <div class="imenu">
          <h6>Dołącz do Twittera już dziś!</h6>
          <a class = "buttons2 btn btn-primary" href="{% url 'login' %}" type="button" name="button">Login</a>
          <br>
          <a class = "buttons2 btn btn-primary" href="{% url 'accounts:signup' %}" type="button" name="button" value="Signup">Signup</a>
        </div>
      </div>
    </div>

    <footer class="ifooter">
      <div>
        <ul class = "list-group list-group-horizontal">
          <li class="list-group-item ifooter">Twitter Clone Project</li>
        </ul>
      </div>
    </footer>
  </div>
{% endblock %}

templates/right_column.html
{% load static %}
{% url 'blog:for_user' username=user_profile.username as profile_page %}

<div class="col-sm-4">
  <div  class = "" id = "right_column">

    <div class="about_me">
        <p style= "padding-left: 25px; padding-top: 10px; color: #1da1f2; width: 100%;"><strong>About me:</strong></p>
        <table>
          <tr>
            <td><a target="_blank" href="#"><i class="fas fa-address-card"> </i>  Website</a></td>
          </tr>
          <tr>
            <td><a target="_blank" href="#"><i class="fab fa-linkedin"> </i>  Linkedin</a></td>
          </tr>
          <tr>
            <td><a target="_blank" href="https://github.com/dawidceg"><i class="fab fa-github-square"> </i>  Github</a></td>
          </tr>
          <tr>
            <td><span id="email"><i class="fas fa-envelope"> </i> <span onclick="copyinfo()" name="copy_pre" id="myemail" data-toggle="tooltip" title="Click two times to copy">cegielski.dawid@wp.pl</span></span><span id="copied" class= "infocopy"> <strong><i class="fas fa-check-square"></i> copied</strong> </span></td>
          </tr>
        </table>
    </div>

    {% if request.get_full_path == profile_page %}
    <div class="overflow-auto users_follow_window" style="width:100%;">

      <div class="row" style="width:100%;">
        <div class="">
          <p style= "padding-left: 40px; padding-top: 10px; color: #1da1f2; width: 100%;"><strong>Followers list:</strong> </p>
        {% for following in user_profile.profile.followers_list %}
            <p class="users_follow_list"><img src="{{following.user.profile.profile_pic.url}}" alt="" class="users_follow_list_logo">
              <span style="padding-left:10px"><strong id = "users_follow_list_nick" onclick = "location.href='{% url 'blog:for_user' username=following %}';">@{{following}}</strong></span></p>
        {% endfor %}
        </div>
      </div>
    </div>
    {% endif %}

  </div>
</div>

templates/search.html
{% extends "home.html" %}
{% block content %}
{% load static %}

<div class="container" style = margin-top:72px>
  <div class="row justify-content-center">

    {% if alltwitts %}
      <div class="col-sm-8">
        <p></p>
        <h6><i class="far fa-lightbulb"></i> You should may check the comments</h6>
        <h6><i class="fas fa-mouse"></i> Click on Tweet to detail</h6>
        <p></p>
        {% for twitt in alltwitts %}

          {% include "blog/_twitt.html" %}

        {% endfor %}
      </div>
    {% else %}

      <div class="col-sm-8">
        <div class="row twitt_list ">
          <h1><span class = "fas fa-sad-tear"></span></h1>
          <h4> Not found any twitts</h4>
        </div>
      </div>

    {% endif %}

    {% include "right_column.html" %}

    </div>
  </div>



{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <div class="container-fluid p-0">
    <div class="container ileft">
        <h4><p><span class="fa fa-search"> </span> Follow what interests you.</p>
          <br><p><span class="fa fa-users"> </span> Find out what others are talking about.</p>
          <br><p><span class="fa fa-comments-o" ></span> Join the conversation.</p>
        </h4>
    </div>
    <div class="container iright">
      <!-- <form class="ilogin" method="post">
        <input id = "abc" type="text" placeholder="Username">
        <input id = "abc" type="text" placeholder="Password">
        <input class = "buttons btn btn-primary" type="submit" name="login" value="Login">
      </form> -->
      <div id = 'signup'>
        <a href="{% url 'home' %}"><img src="{% static  'img/logo.png' %}" alt="logo"></a>
        <h4><b>See what's happening in the world right now</b></h4><br>
        <div class="imenu">
          <h6>Join Twitter today!</h6>
          <a class = "buttons2 btn btn-primary" href="{% url 'login' %}" type="button" name="button">Login</a>
          <br>
          <a class = "buttons2 btn btn-primary" href="{% url 'accounts:signup' %}" type="button" name="button" value="Signup">Signup</a>
        </div>
      </div>
    </div>

    <footer class="ifooter">
      <div>
        <ul class = "list-group list-group-horizontal">
          <li class="list-group-item ifooter">Twitter Clone Project</li>
        </ul>
      </div>
    </footer>
  </div>
{% endblock %}